import { useCallback, useEffect, useState } from 'react'
import { supabase } from '../../lib/supabase'
import { copyText, formatDate } from '../../lib/format'
import type { License, LicenseDevice, Product } from '../../lib/types'
import { Badge, PageTitle, Spinner } from '../../components/ui'

export function AdminLicenses(): JSX.Element {
  const [licenses, setLicenses] = useState<License[]>([])
  const [devices, setDevices] = useState<Record<string, LicenseDevice[]>>({})
  const [products, setProducts] = useState<Product[]>([])
  const [users, setUsers] = useState<Record<string, { email: string; full_name: string | null }>>({})
  const [loading, setLoading] = useState(true)
  const [creating, setCreating] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [copiedId, setCopiedId] = useState<string | null>(null)
  const [form, setForm] = useState({ user_email: '', product_id: '', label: '', max_devices: '2' })

  const load = useCallback(async () => {
    const [licRes, prodRes, userRes] = await Promise.all([
      supabase.from('licenses').select('*').order('created_at', { ascending: false }).limit(300),
      supabase.from('products').select('*').order('name'),
      supabase.from('profiles').select('id, email, full_name')
    ])
    const rows = (licRes.data as License[]) ?? []
    setLicenses(rows)

    const deviceMap: Record<string, LicenseDevice[]> = {}
    if (rows.length > 0) {
      const { data: devData } = await supabase
        .from('license_devices')
        .select('*')
        .in('license_id', rows.map((r) => r.id))
      for (const d of (devData as LicenseDevice[]) ?? []) {
        ;(deviceMap[d.license_id] ??= []).push(d)
      }
    }
    setDevices(deviceMap)

    setProducts((prodRes.data as Product[]) ?? [])
    const userMap: Record<string, { email: string; full_name: string | null }> = {}
    for (const u of (userRes.data as { id: string; email: string; full_name: string | null }[]) ?? []) {
      userMap[u.id] = { email: u.email, full_name: u.full_name }
    }
    setUsers(userMap)
    setLoading(false)
  }, [])

  useEffect(() => {
    void load()
  }, [load])

  async function createLicense(): Promise<void> {
    const email = form.user_email.trim().toLowerCase()
    if (!email) {
      setError('Enter the buyer’s email.')
      return
    }
    const user = Object.entries(users).find(([, u]) => u.email.toLowerCase() === email)
    if (!user) {
      setError(`No user with email ${email} — they must login first.`)
      return
    }
    setCreating(true)
    setError(null)
    // Key is generated by the database default (see SQL migration).
    const { error: insertError } = await supabase.from('licenses').insert({
      user_id: user[0],
      product_id: form.product_id || null,
      label: form.label.trim() || 'License',
      max_devices: Math.max(1, Number(form.max_devices) || 2),
      status: 'active'
    })
    setCreating(false)
    if (insertError) {
      setError(insertError.message)
      return
    }
    setForm({ user_email: '', product_id: '', label: '', max_devices: '2' })
    await load()
  }

  async function setStatus(license: License, status: 'active' | 'revoked'): Promise<void> {
    const action = status === 'revoked' ? 'Revoke' : 'Reactivate'
    if (!window.confirm(`${action} "${license.label}"? Devices will ${status === 'revoked' ? 'be blocked' : ' work again'}.`))
      return
    const { error: err } = await supabase.from('licenses').update({ status }).eq('id', license.id)
    if (err) setError(err.message)
    else await load()
  }

  async function revokeDevice(device: LicenseDevice): Promise<void> {
    if (!window.confirm(`Revoke this device? (${device.device_id.slice(0, 18)}…)`)) return
    const { error: err } = await supabase.from('license_devices').update({ revoked: true }).eq('id', device.id)
    if (err) setError(err.message)
    else await load()
  }

  async function copyKey(license: License): Promise<void> {
    const ok = await copyText(license.key)
    setCopiedId(ok ? license.id : null)
    setTimeout(() => setCopiedId(null), 2000)
  }

  if (loading) return <Spinner label="Loading licenses…" />

  return (
    <div>
      <PageTitle title="Licenses" subtitle="Issue activation keys and control devices." />

      <div className="card mb-6 p-5">
        <h2 className="flex items-center gap-2 font-bold text-slate-900">
          <i className="fa-solid fa-key text-brand-600" aria-hidden="true" />
          Issue a new license
        </h2>
        <div className="mt-3 grid gap-3 sm:grid-cols-4">
          <div>
            <label className="label">Buyer email *</label>
            <input
              className="input"
              placeholder="buyer@email.com"
              value={form.user_email}
              onChange={(e) => setForm({ ...form, user_email: e.target.value })}
            />
          </div>
          <div>
            <label className="label">Tool</label>
            <select
              className="input"
              value={form.product_id}
              onChange={(e) => setForm({ ...form, product_id: e.target.value })}
            >
              <option value="">— General —</option>
              {products.map((p) => (
                <option key={p.id} value={p.id}>
                  {p.name}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label className="label">Label</label>
            <input
              className="input"
              placeholder="e.g. Firefox Automation Manager"
              value={form.label}
              onChange={(e) => setForm({ ...form, label: e.target.value })}
            />
          </div>
          <div>
            <label className="label">Devices</label>
            <input
              className="input"
              type="number"
              min={1}
              value={form.max_devices}
              onChange={(e) => setForm({ ...form, max_devices: e.target.value })}
            />
          </div>
        </div>
        {error && (
          <div className="mt-3 rounded-xl bg-red-50 px-3 py-2.5 text-sm text-red-600" role="alert">
            {error}
          </div>
        )}
        <button className="btn-primary mt-4" onClick={() => void createLicense()} disabled={creating}>
          <i className={creating ? 'fa-solid fa-spinner fa-spin' : 'fa-solid fa-key'} aria-hidden="true" />
          {creating ? 'Creating…' : 'Create License'}
        </button>
      </div>

      <div className="card overflow-x-auto">
        <table className="w-full min-w-[820px] text-left text-sm">
          <thead className="border-b border-slate-100 bg-slate-50/60 text-xs uppercase tracking-wide text-slate-500">
            <tr>
              <th className="px-5 py-3.5">Key</th>
              <th className="px-5 py-3.5">Label</th>
              <th className="px-5 py-3.5">Owner</th>
              <th className="px-5 py-3.5">Devices</th>
              <th className="px-5 py-3.5">Status</th>
              <th className="px-5 py-3.5">Created</th>
              <th className="px-5 py-3.5">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100">
            {licenses.map((l) => {
              const devs = devices[l.id] ?? []
              const active = devs.filter((d) => !d.revoked)
              return (
                <tr key={l.id} className="hover:bg-slate-50/60">
                  <td className="px-5 py-3.5">
                    <div className="flex items-center gap-2">
                      <code className="font-mono text-xs text-slate-600">{l.key.slice(0, 18)}…</code>
                      <button
                        className="text-xs font-semibold text-brand-600 hover:underline"
                        onClick={() => void copyKey(l)}
                      >
                        <i className={copiedId === l.id ? 'fa-solid fa-check' : 'fa-solid fa-copy'} aria-hidden="true" />
                        {copiedId === l.id ? 'Copied' : 'Copy'}
                      </button>
                    </div>
                  </td>
                  <td className="px-5 py-3.5 font-semibold text-slate-800">{l.label}</td>
                  <td className="px-5 py-3.5">
                    <div className="text-xs text-slate-500">{users[l.user_id]?.full_name ?? '—'}</div>
                    <div className="text-xs text-slate-400">{users[l.user_id]?.email}</div>
                  </td>
                  <td className="px-5 py-3.5">
                    <div className="text-xs font-bold text-slate-700">
                      {active.length}/{l.max_devices}
                    </div>
                    {devs.length > 0 && (
                      <details className="mt-1">
                        <summary className="cursor-pointer text-[11px] font-semibold text-brand-600">
                          View devices
                        </summary>
                        <div className="mt-1 space-y-1">
                          {devs.map((d) => (
                            <div
                              key={d.id}
                              className="flex items-center justify-between gap-2 rounded bg-slate-50 px-2 py-1 text-[10px]"
                            >
                              <span className="truncate font-mono">{d.device_id.replace(/^dev_/, '').slice(0, 12)}…</span>
                              <button
                                className="font-bold text-red-500 hover:underline"
                                disabled={d.revoked}
                                onClick={() => void revokeDevice(d)}
                              >
                                {d.revoked ? 'Revoked' : 'Revoke'}
                              </button>
                            </div>
                          ))}
                        </div>
                      </details>
                    )}
                  </td>
                  <td className="px-5 py-3.5">
                    <Badge tone={l.status === 'active' ? 'green' : 'red'}>{l.status}</Badge>
                  </td>
                  <td className="px-5 py-3.5 text-slate-500">{formatDate(l.created_at)}</td>
                  <td className="px-5 py-3.5">
                    <button
                      className={l.status === 'active' ? 'btn-danger px-3 py-1.5 text-xs' : 'btn-primary px-3 py-1.5 text-xs'}
                      onClick={() => void setStatus(l, l.status === 'active' ? 'revoked' : 'active')}
                    >
                      <i
                        className={l.status === 'active' ? 'fa-solid fa-ban' : 'fa-solid fa-rotate-left'}
                        aria-hidden="true"
                      />
                      {l.status === 'active' ? 'Revoke' : 'Restore'}
                    </button>
                  </td>
                </tr>
              )
            })}
            {licenses.length === 0 && (
              <tr>
                <td className="px-5 py-8 text-center text-slate-400" colSpan={7}>
                  No licenses issued yet.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  )
}
